```{r}
#driverEntryId=22431
driverCode = cars[cars$entryId==driverEntryId,'code']
```
## Driver Report, `r stage_code`  - `r driverCode`

Stage report for `r driverCode`.

### Rebased Split Times

`r driverCode`'s delta at each split compared to other drivers.

```{r}
# Pass in driverId
driverCode = cars[cars$entryId==driverEntryId,'code']
driver_rebased = rebase(full_splits_wide, driverCode,
                       split_names, id_col='code') %>%
                  select(code, all_of(split_names)) %>%
                  filter_at(vars(starts_with("split_")),
                                all(isna(.)))

split_N_col_idx = which(colnames(driver_rebased) == 'split_N')[[1]]
formattable(driver_rebased[,c('code',split_names)], align='c',
            list(area(col = 2:split_N_col_idx) ~ color_tile2(c("green",'white',"red")),
                 entryId=FALSE))
```

### Within-Split Duration Deltas

`r driverCode`'s delta in time to complete each split section compared to other drivers:

```{r}
# Pass in driverId

driver_rebased = rebase(full_durations_wide, driverCode,
                       split_names, id_col='code')

split_N_col_idx = which(colnames(driver_rebased) == 'split_N')[[1]]
formattable(driver_rebased[,c('code',split_names)], align='c',
            list(area(col = 2:split_N_col_idx) ~ color_tile2(c("green",'white',"red")),
                 entryId=FALSE))
```

