
```{r setup, warning=FALSE, include=FALSE, echo=FALSE, message=FALSE, output=FALSE}
library(knitr)
library(formattable)

source('_code/wrc-api.R')
source('_code/wrc-wrangling.R')
source('_code/wrc-charts.R')
source('timing_sketches.R')
```

```{r init_vars, warning=FALSE, include=FALSE, echo=FALSE, message=FALSE, output=FALSE}
# Load in event data
s = get_active_season()
eventId = get_eventId_from_name(s, 'croatia')

itinerary = get_itinerary(eventId)
sections = get_sections(itinerary)
stages = get_stages(sections) #status and code are useful...
stages_lookup = get_stages_lookup(stages)

stage_cols = c('stageId', 'number', 'name', 'distance', 'code')
stage_info = stages %>%
                select(all_of(stage_cols)) %>%
                # Tidy up the stage name
                mutate(name = str_replace(name, ' \\(Live TV\\)', ''))
  
# For driver details
entries = get_rally_entries(eventId)
cars = get_car_data(entries)

# We can have customer entries which mess things up...
wrc = cars %>% filter(entryId<+22439)
wrc_entries = wrc$entryId
```

```{r looper, message=FALSE, echo=FALSE, error=FALSE, warning=FALSE, results='asis'}

stage_list=list("SS1", "SS2", "SS3", "SS4", "SS5", "SS6", "SS7", "SS8", "SS9", "SS10", "SS11", "SS12", "SS13", "SS14", "SS15", "SS16")

omit_stage_splits = c()

#stage_list=list("SS1","SS2")
for (stage_code in stage_list){
  stageId = stages_lookup[[stage_code]]
  stage_times = get_stage_times(eventId, stageId)

  stage_info_ = stage_info[stage_info['stageId']==stageId,]
  
  src = knit_expand("stage_result_template.Rmd")
    cat(knit_child(text=src,
                 options = list(echo=FALSE, warning=FALSE, error=FALSE),
                 quiet=TRUE))

}
```

